name: oalab_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - conda-forge
dependencies:
  - python
  - openalea.core
  - ipython
  - qtconsole
  - configobj
  - pip
  - pip:
      - -e '..[test,dev,doc]'
